query GetAllIndexPageData {
	lmke_dev {
		picture {
			id
		}
		name
		subtitle
		github_link
		email
		about_me
	}

	lmke_skills(filter: { hidden: { _neq: true } }) {
		name
	}

	lmke_projects(filter: { discontinued: { _neq: true } }) {
		logo {
			id
		}
		title
		description
		link
		link_source
	}

	lmke_friends {
		name
		activity
		image_url
		link_web
		link_gh
	}

	lmke_article_topics {
		name
	}
	
	lmke_articles(limit: 1, sort: ["-date_published"]) {
		id
		slug
		date_created
		date_updated
		date_published
		user_created {
			first_name
			last_name
			avatar {
				id
			}
		}
		preview_image {
			id
			source
		}
		wallpaper_image {
			id
			source
		}
		title
		topics {
			topic { name }
		}
		description
	}
}